[options]
addons_path = /mnt/addons_library
data_dir = /var/lib/odoo
proxy_mode = True
admin_passwd = $pbkdf2-sha512$600000$/1.L0Zrzfq.Vck7p/V.L8Q$c6hDsQYoE59V6gq53UgFUQw3UeEDULA9SYRI0EELbgKfc2nDaSNUfQ91.CCqVRI9rZdmn6yJRCrKYAagRBfbIg

